apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
   metadata:
    labels:
      app: frontend
   spec:
    containers:
    - image: prabhuraja/hello:${env.BUILD_ID}
      name: frontend


